name: prueba_rick
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  bpstate:
    git: 'https://github.com/vpanchojs/bpstate'
  flutter_localizations:
    sdk: flutter
  go_router: ^14.6.3  
  dio: ^5.7.0
  rxdart: ^0.28.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true
